name: docker build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      status: ${{ steps.check-status.outputs.status }}
      version: ${{ steps.check-status.outputs.version }}
      tag: ${{ steps.check-status.outputs.tag }}
    steps:
      - name: Check if build required
        id: check-status
        run: |
          RELEASE_DATA=$(curl -s https://api.github.com/repos/DEvmIb/telerising-builds/releases/latest)
          TAG=$(echo "$RELEASE_DATA" | jq -r '.tag_name')
          VERSION=$(echo "$TAG" | cut -c2- | grep -oE 'v[0-9]+(\.[0-9]+)+' | sed 's/^v//')

          if docker pull ghcr.io/lucasheld/telerising-api:latest; then
            LAST_VERSION=$(docker inspect ghcr.io/lucasheld/telerising-api:latest | jq -r '.[0].Config.Labels.VERSION')
          else
            LAST_VERSION=""
          fi
          echo "last version: $LAST_VERSION"

          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "tag=$TAG" >> $GITHUB_OUTPUT
          
          if [ "${VERSION}" == "${LAST_VERSION}" ]; then
            echo "version already pushed"
            echo "status=old" >> $GITHUB_OUTPUT
          else
            echo "version is not pushed"
            echo "status=new" >> $GITHUB_OUTPUT
          fi

  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    needs: check
    if: needs.check.outputs.status == 'new'
    name: Build docker image
    steps:
      - name: Login
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and export to Docker
        uses: docker/build-push-action@v7
        with:
          load: true
          build-args: |
            TAG=${{ matrix.tag }}
            VERSION=${{ matrix.version }}
          tags: ghcr.io/lucasheld/telerising-api:test

      - name: Run
        run: |
          docker run --rm -it -d -p 5000:5000 --name telerising-api ghcr.io/lucasheld/telerising-api:test

      - name: Test
        uses: nick-fields/retry@v4
        with:
          timeout_seconds: 1
          max_attempts: 10
          command: curl http://127.0.0.1:5000/

      - name: Stop
        run: |
          docker stop telerising-api

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          platforms: linux/amd64,linux/arm64
          provenance: false
          sbom: false
          push: true
          build-args: |
            TAG=${{ needs.check.outputs.tag }}
            VERSION=${{ needs.check.outputs.version }}
          tags: |
            ghcr.io/lucasheld/telerising-api:latest
            ghcr.io/lucasheld/telerising-api:${{ needs.check.outputs.version }}
